# Cart Service - Development Environment Configuration

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://localhost:5434/cartdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8084

# API Key for authentication (Development)
api:
  key: cart-service-dev-api-key

# Logging configuration
logging:
  level:
    com.farmatodo.cart_service: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
